// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBm0Y35aEcmgJj8Ruo8M98f-a5t49f5vA',
    appId: '1:1027439348042:web:e195deaf4655f0134a59b3',
    messagingSenderId: '1027439348042',
    projectId: 'cartsy-172ca',
    authDomain: 'cartsy-172ca.firebaseapp.com',
    storageBucket: 'cartsy-172ca.firebasestorage.app',
    measurementId: 'G-E7DY5ZN41G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJULCW5b-XurwKwnZDMb0p8kE9hoJNrk',
    appId: '1:1027439348042:android:43793a06dafbcc814a59b3',
    messagingSenderId: '1027439348042',
    projectId: 'cartsy-172ca',
    storageBucket: 'cartsy-172ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVn4o32C_fERZMzGKwO_r0Z5UB50Zvls',
    appId: '1:1027439348042:ios:403799be208727ae4a59b3',
    messagingSenderId: '1027439348042',
    projectId: 'cartsy-172ca',
    storageBucket: 'cartsy-172ca.firebasestorage.app',
    iosClientId: '1027439348042-t2av5rk03t7ekuh8e1io4k4ecof04tmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVn4o32C_fERZMzGKwO_r0Z5UB50Zvls',
    appId: '1:1027439348042:ios:403799be208727ae4a59b3',
    messagingSenderId: '1027439348042',
    projectId: 'cartsy-172ca',
    storageBucket: 'cartsy-172ca.firebasestorage.app',
    iosClientId: '1027439348042-t2av5rk03t7ekuh8e1io4k4ecof04tmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBm0Y35aEcmgJj8Ruo8M98f-a5t49f5vA',
    appId: '1:1027439348042:web:b6b5fd21fc262fc34a59b3',
    messagingSenderId: '1027439348042',
    projectId: 'cartsy-172ca',
    authDomain: 'cartsy-172ca.firebaseapp.com',
    storageBucket: 'cartsy-172ca.firebasestorage.app',
    measurementId: 'G-RXKJ0PPF2C',
  );
}
